export const theme = {
  backgroundPrincipal: "#E5E5E5",
  colorWhite: "#FFFFFF",
  colorPrincipal: "#FEFEFE",
  backgroundPrincipalDarkMode: "#1F1F31",
  backgroundBtnFooterMenu: "#F5F5F5", 
  colorForgotLink: "rgba(35, 34, 50, 0.8)",
  colorDarkModeForgotLink: "rgba(254, 254, 254, 0.8)",
  colorPrincipalDarkMode: "#FEFEFE",
  backgroundLoginFieldDarkMode: "#2F2F43",
  colorFieldDarkMode: "#2F2F43",
  backgroundDarkModeHistoryCards: "#2c2c47",
  backgroundBtnModeDarkMode: "#222243",
  colorRemoveIcon: "#d36060",
  backgroundNavbarDarkMode: "#2C2B3E",
  colorDescriptionsHistory: "#232232",
  colorTextDate: "#161617",
  generalFont: "Inter, system-ui, Avenir, Helvetica, Arial, sans-serif",
};
